# 模型配置
models:
  lstm_model:
    type: lstm
    input_shape: [100, 1]  # LSTM 模型的输入形状，序列长度为100，单变量
    units: 64  # LSTM单元数量
    layers:
      - LSTM:
          units: 64
          return_sequences: true
      - LSTM:
          units: 32
      - Dense:
          units: 1  # 输出单变量的预测

  gru_model:
    type: gru
    input_shape: [50, 1]  # GRU 模型的输入形状，序列长度为50
    units: 64  # GRU单元数量
    layers:
      - GRU:
          units: 64
          return_sequences: true
      - GRU:
          units: 32
      - Dense:
          units: 1  # 单步预测

  transformer_model:
    type: transformer
    input_shape: [200, 1]  # Transformer 模型的输入形状，序列长度为200
    num_layers: 2
    d_model: 64
    num_heads: 4
    dff: 256
    dropout_rate: 0.1
    output_units: 1  # 单变量的单步预测

# 训练配置
training:
  lstm_model:
    optimizer: adam
    loss: mean_squared_error
    metrics: [mae]
    epochs: 30
    batch_size: 64
    learning_rate: 0.001

  gru_model:
    optimizer: adam
    loss: mean_squared_error
    metrics: [mae]
    epochs: 30
    batch_size: 64
    learning_rate: 0.001

  transformer_model:
    optimizer: adam
    loss: mean_squared_error
    metrics: [mae]
    epochs: 40
    batch_size: 32
    learning_rate: 0.0001

# 数据预处理配置
preprocessing:
  normalize: true
  scaling_method: "minmax"
  default_window_size: 100  # 默认窗口大小

# 提前期预测配置
forecasting:
  forecast_horizon: 1